version: '3'
services:
  fitness_db:
    container_name: fitness_db
    restart: always
    image: mariadb
    command: --max_allowed_packet=4000M
    environment:
      MYSQL_DATABASE: 'fitness_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'user'
    ports:
      - "3306:3306"
    volumes:
      - "./database-volume:/var/lib/mysql"
